### ISSUE TITLE
How to handle api path parameters?

### ISSUE THREAD

**Issue by micaelomota** [ghzcool/swagger-react-generator#1]
Hi, thanks for the lib. It's really nice tool.

I'm wondering how we can generate APIs with path parameters, for instance `/users/{userId}/wallets` 🤔.

The current behaviour is basically ignoring the parameter .

**Comment by ghzcool** [comment]
Please provide part of swagger.json so I check it and improve.

**Comment by ghzcool** [comment]
Example:

"/store/order/{orderId}"

"parameters": [
          {
            "name": "orderId",
            "in": "path",
            "description": "ID of pet that needs to be fetched",
            "required": true,
            "type": "integer",
            "maximum": 10,
            "minimum": 1,
            "format": "int64"
          }
        ]

 "in": "path"
defines where this parameter should be taken from

generated result:

this.storeOrderOrderIdGet = (orderId, options = {}) => {
        const {fetchMethod, basePath, headers, getHeaders} = this.config;
        let url = '/store/order/{orderId}';
        url = url.split(['{', '}'].join('orderId')).join(encodeURIComponent(String(orderId)));
...
